# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/digital-technologies',
                'doc_host': 'https://dochemer.github.io',
                'git_url': 'https://github.com/dochemer/digital-technologies',
                'lib_path': 'digital_technologies'},
  'syms': {'digital_technologies.core': {'digital_technologies.core.foo': ('core.html#foo', 'digital_technologies/core.py')}}}
